[[main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[main]]
    identifier = "category"
    name = "Archives"
    url = "/posts/"
    weight = 2
[[main]]
    identifier = "category1"
    name = "ğŸ“ Articles"
    url = "/categories/article"
    parent = "category"
    weight = 1
[[main]]
    identifier = "category2"
    name = "â­ï¸ Bookmarks"
    url = "/categories/bookmarks"
    parent = "category"
    weight = 2
[[main]]
    identifier = "category3"
    name = " ğŸ“… RSVPs"
    url = "/categories/rsvp"
    parent = "category"
    weight = 3
[[main]]
    identifier = "category4"
    name = "ğŸ’¼ Statuses"
    url = "/categories/status"
    parent = "category"
    weight = 3
[[main]]
    identifier = "category5"
    name = "ğŸš© Check-in"
    url = "/categories/checkin"
    parent = "category"
    weight = 4
[[main]]
    identifier = "category6"
    name = "ğŸ’¬ Replies"
    url = "/categories/reply"
    parent = "category"
    weight = 5
[[main]]
    identifier = "category7"
    name = "ğŸ† Sports"
    url = "/categories/sport"
    parent = "category"
    weight = 6
[[main]]
    identifier = "category8"
    name = "ğŸ‘ Favourites"
    url = "/categories/favourite"
    parent = "category"
    weight = 7
[[main]]
    identifier = "category9"
    name = "ğŸ”„ Reposts"
    url = "/categories/repost"
    parent = "category"
    weight = 8
[[main]]
    identifier = "category10"
    name = "ğŸ“· Photos"
    url = "/categories/photo"
    parent = "category"
    weight = 9

[[main]]
  identifier = "Projects"
  name = "Projects"
  url = "/projects"
  weight = 3

[[main]]
  identifier = "News"
  name = "News"
  url = "/news"
  weight = 4

[[main]]
  identifier = "About"
  name = "About"
  url = "/about"
  weight = 5

[[main]]
  name = "Search"
  url = "/search"
  weight = 6
