[[main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[main]] # parent menus
    identifier = "category"
    name = "Archives"
    url = "/posts/"
    weight = 2
        [[main]] # child menus
            identifier = "category1"
            name = "ğŸ“ Articles"
            url = "/categories/article"
            parent = "category"
            weight = 1
        [[main]]
            identifier = "category2"
            name = "â­ï¸ Bookmarks"
            url = "/categories/bookmarks"
            parent = "category"
            weight = 2
        [[main]]
            identifier = "category3"
            name = " ğŸ“… RSVPs"
            url = "/categories/rsvp"
            parent = "category"
            weight = 3
        [[main]]
            identifier = "category4"
            name = "ğŸ’¼ Statuses"
            url = "/categories/status"
            parent = "category"
            weight = 3
        [[main]]
            identifier = "category5"
            name = "ğŸš© Check-in"
            url = "/categories/checkin"
            parent = "category"
            weight = 4
        [[main]]
            identifier = "category6"
            name = "ğŸ’¬ Replies"
            url = "/categories/reply"
            parent = "category"
            weight = 5
        [[main]]
            identifier = "category7"
            name = "ğŸ† Sports"
            url = "/categories/sport"
            parent = "category"
            weight = 6
        [[main]]
            identifier = "category8"
            name = "ğŸ‘ Favourites"
            url = "/categories/favourite"
            parent = "category"
            weight = 7
        [[main]]
            identifier = "category9"
            name = "ğŸ”„ Reposts"
            url = "/categories/repost"
            parent = "category"
            weight = 8
        [[main]]
            identifier = "category10"
            name = "ğŸ“· Photos"
            url = "/categories/photo"
            parent = "category"
            weight = 9

[[main]]
  identifier = "Projects"
  name = "Projects"
  url = "/projects"
  weight = 3

[[main]]
  identifier = "About"
  name = "About"
  url = "/about"
  weight = 4
    [[main]]
    identifier = "About1"
    name = "ğŸ› ï¸ Changelog"
    url = "about/changelog"
    weight = 1
    parent = "About"
    [[main]]
    identifier = "About2"
    name = "âš–ï¸ License"
    url = "about/license"
    weight = 2
    parent = "About"
    [[main]]
    identifier = "About3"
    name = "â˜” Disclaimer"
    url = "about/disclaimer"
    weight = 3
    parent = "About"
    [[main]]
    identifier = "About4"
    name = "â˜ï¸ Contact"
    url = "about/contact"
    weight = 4
    parent = "About"


[[main]]
  identifier = "Others"
  name = "Others"
  url = "/others"
  weight = 5
    [[main]]
    identifier = "Others1"
    name = "ğŸ“° News"
    url = "others/news"
    weight = 1
    parent = "Others"
    [[main]]
    identifier = "Others2"
    name = "ğŸ˜ Talk"
    url = "others/talk"
    weight = 2
    parent = "Others"
    [[main]]
    identifier = "Others3"
    name = "ğŸ“š Reading"
    url = "others/reading"
    weight = 3
    parent = "Others"
    [[main]]
    identifier = "Others4"
    name = "ğŸ“º Watching"
    url = "others/video"
    weight = 4
    parent = "Others"
    [[main]]
    identifier = "Others5"
    name = "ğŸ® Gaming"
    url = "others/gaming"
    weight = 5
    parent = "Others"
    [[main]]
    identifier = "Others7"
    name = "ğŸ›’ Marketplace"
    url = "others/marketplace"
    weight = 6
    parent = "Others"

[[main]]
  name = "Search"
  url = "/search"
  weight = 6
